<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sampletestobject</name>
   <tag></tag>
   <elementGuidId>00b011cc-c4e6-4ded-84c7-af1f2f0d95df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[class=&quot;product_sort_container&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
